# Generated by Django 2.1.5 on 2019-02-16 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop101', '0002_auto_20190216_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='Product_name',
        ),
    ]
