# Generated by Django 2.1.5 on 2019-02-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop101', '0003_auto_20190216_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Product_name',
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='product_untitled', max_length=190),
            preserve_default=False,
        ),
    ]
